/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'WarehouseList': RouteRecordInfo<'WarehouseList', '/almacenes', Record<never, never>, Record<never, never>>,
    'almacenes-components-warehouse-drawer': RouteRecordInfo<'almacenes-components-warehouse-drawer', '/almacenes/components/WarehouseDrawer', Record<never, never>, Record<never, never>>,
    'CategoryList': RouteRecordInfo<'CategoryList', '/categorias', Record<never, never>, Record<never, never>>,
    'categorias-components-category-drawer': RouteRecordInfo<'categorias-components-category-drawer', '/categorias/components/CategoryDrawer', Record<never, never>, Record<never, never>>,
    'CustomerList': RouteRecordInfo<'CustomerList', '/clientes', Record<never, never>, Record<never, never>>,
    'clientes-components-client-drawer': RouteRecordInfo<'clientes-components-client-drawer', '/clientes/components/ClientDrawer', Record<never, never>, Record<never, never>>,
    'QuotesList': RouteRecordInfo<'QuotesList', '/cotizaciones', Record<never, never>, Record<never, never>>,
    'cotizaciones-gestionar': RouteRecordInfo<'cotizaciones-gestionar', '/cotizaciones/gestionar', Record<never, never>, Record<never, never>>,
    'cotizaciones-gestionar-id': RouteRecordInfo<'cotizaciones-gestionar-id', '/cotizaciones/gestionar/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ChangePassword': RouteRecordInfo<'ChangePassword', '/cuenta', Record<never, never>, Record<never, never>>,
    'InvoicesList': RouteRecordInfo<'InvoicesList', '/facturas', Record<never, never>, Record<never, never>>,
    'ExpensesList': RouteRecordInfo<'ExpensesList', '/gastos', Record<never, never>, Record<never, never>>,
    'gastos-components-expense-drawer': RouteRecordInfo<'gastos-components-expense-drawer', '/gastos/components/ExpenseDrawer', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'Manifests': RouteRecordInfo<'Manifests', '/manifiestos', Record<never, never>, Record<never, never>>,
    'ProductList': RouteRecordInfo<'ProductList', '/productos', Record<never, never>, Record<never, never>>,
    'ProductEdit': RouteRecordInfo<'ProductEdit', '/productos/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'productos-catalogo-imprimir': RouteRecordInfo<'productos-catalogo-imprimir', '/productos/catalogo/imprimir', Record<never, never>, Record<never, never>>,
    'productos-components-product-form': RouteRecordInfo<'productos-components-product-form', '/productos/components/ProductForm', Record<never, never>, Record<never, never>>,
    'ProductCreate': RouteRecordInfo<'ProductCreate', '/productos/crear', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'TicketsList': RouteRecordInfo<'TicketsList', '/vales', Record<never, never>, Record<never, never>>,
    'vales-components-abono-dialog': RouteRecordInfo<'vales-components-abono-dialog', '/vales/components/AbonoDialog', Record<never, never>, Record<never, never>>,
    'vales-components-abonos-view-dialog': RouteRecordInfo<'vales-components-abonos-view-dialog', '/vales/components/AbonosViewDialog', Record<never, never>, Record<never, never>>,
    'vales-components-pay-vale-dialog': RouteRecordInfo<'vales-components-pay-vale-dialog', '/vales/components/PayValeDialog', Record<never, never>, Record<never, never>>,
    'vales-components-vale-drawer': RouteRecordInfo<'vales-components-vale-drawer', '/vales/components/ValeDrawer', Record<never, never>, Record<never, never>>,
  }
}
